apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-deployment
  template:
    metadata:
      labels:
        app: argocd-deployment
    spec:
      containers:
      - name: argocd-deployment
        image: mdrayaanpasha/argocd:2ccd3ea
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: argocd-service
spec:
  selector:
    app: argocd-deployment
  ports:
  - port: 3000
    targetPort: 3000
  type: ClusterIP
