name: Build and Deploy (GitOps)

on:
  push:
    branches:
      - main

jobs:
  build-push-and-update-manifest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set image tag
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build image
        run: docker build -t mdrayaanpasha/argocd:${{ env.IMAGE_TAG }} ./K8s

      - name: Push image
        run: docker push mdrayaanpasha/argocd:${{ env.IMAGE_TAG }}

      - name: Update Kubernetes manifest
        run: |
          sed -i "s|image: mdrayaanpasha/argocd:.*|image: mdrayaanpasha/argocd:${IMAGE_TAG}|g" K8s/deployment.yml

      - name: Commit and push manifest update
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add K8s/deployment.yml
          git commit -m "deploy: image ${IMAGE_TAG}"
          git push
